<a href="https://colab.research.google.com/github/kushum-coder/2501460_kushum/blob/main/Worksheet1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Problem 1
import numpy as np

# 1
a = np.array([[1, 2], [3, 4]])
print(a)

# 2
b = np.ones((4, 2))
print(b)

# 3
c = np.full((2, 2), 4)
print(c)

# 4
d = np.zeros_like(a)
print(d)

# 5
e = np.ones_like(a)
print(e)

# 6
new_list = [1, 2, 3, 4]
arr = np.array(new_list)
print(arr)


[[1 2]
 [3 4]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[4 4]
 [4 4]]
[[0 0]
 [0 0]]
[[1 1]
 [1 1]]
[1 2 3 4]


In [ ]:
# Problem 2
import numpy as np

arr = np.arange(10, 50)
print(arr)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
import numpy as np

arr = np.arange(0, 9)
print(arr)

matrix = arr.reshape(3, 3)
print(matrix)


[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
import numpy as np

identity_matrix = np.eye(3)
print(identity_matrix)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
import numpy as np

arr = np.random.random(30)
mean_value = arr.mean()

print("Array:", arr)
print("Mean:", mean_value)



Array: [0.34051303 0.51088224 0.74123325 0.74928332 0.05160045 0.82035187
 0.22688858 0.96133905 0.50410608 0.98245146 0.36584563 0.19198081
 0.07615704 0.97179951 0.38288053 0.06184322 0.32409472 0.83298349
 0.64455741 0.07100671 0.38728155 0.25405518 0.67726318 0.03994017
 0.75387927 0.8987616  0.53239562 0.89873161 0.03215178 0.95363347]
Mean: 0.5079963949942347


In [ ]:
import numpy as np

arr = np.random.random((10, 10))
print(arr)

min_value = arr.min()
max_value = arr.max()

print("Minimum value:", min_value)
print("Maximum value:", max_value)


[[0.85832583 0.87036607 0.92632452 0.81603332 0.34050837 0.11337218
  0.38628273 0.16361868 0.93540947 0.30986845]
 [0.60430465 0.51807089 0.16293224 0.67406071 0.45985499 0.59011988
  0.83595624 0.53240838 0.23695719 0.9888478 ]
 [0.74387858 0.93735091 0.76571042 0.33828444 0.62265189 0.42946492
  0.64117772 0.79546397 0.40251318 0.18303606]
 [0.57869815 0.01140716 0.76356095 0.94539164 0.21208322 0.35262442
  0.72884694 0.73585257 0.20701095 0.70069411]
 [0.67549701 0.4768565  0.87332221 0.84215094 0.80585926 0.97529568
  0.87660606 0.86979052 0.50694483 0.39451756]
 [0.91553389 0.98615027 0.28394484 0.16052902 0.03289329 0.53537903
  0.50306961 0.58169767 0.75320876 0.14234632]
 [0.03618157 0.74421317 0.95683726 0.49577321 0.71712464 0.56923615
  0.35151222 0.30570848 0.60923096 0.64288168]
 [0.67674378 0.70210924 0.3766566  0.74664851 0.28420944 0.76710524
  0.70774263 0.78172669 0.13685553 0.83078119]
 [0.46219751 0.46312689 0.18891347 0.06434131 0.26730706 0.38081912
  0.27902286

In [ ]:
import numpy as np

arr = np.zeros(10)
print(arr)

arr[4] = 1
print(arr)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [ ]:
import numpy as np

arr = [1, 2, 0, 0, 4, 0]

reversed_arr = np.flip(arr)
print(reversed_arr)


[0 4 0 0 2 1]


In [ ]:
import numpy as np

rows, cols = 5, 5
arr = np.ones((rows, cols), dtype=int)

# Set inner elements to 0
arr[1:-1, 1:-1] = 0

print(arr)


[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [ ]:
import numpy as np

# Create an 8x8 checkerboard pattern
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1  # odd rows, even columns
checkerboard[::2, 1::2] = 1  # even rows, odd columns

print(checkerboard)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [ ]:
# Problem 3
import numpy as np

# Arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# 1. Addition
addition = x + y
print("x + y:\n", addition)

# 2. Subtraction
subtraction = x - y
print("x - y:\n", subtraction)

# 3. Multiplication
multiplication = x * 3
multiplication_v = v * 2
print("x * 3:\n", multiplication)
print("v * 2:\n", multiplication_v)

# 4. Square
square_x = x ** 2
print("x squared:\n", square_x)

# 5. Dot products
dot_vw = np.dot(v, w)
print("Dot product between v and w:", dot_vw)

dot_xv = np.dot(x, v)
print("Dot product between x and v:\n", dot_xv)

dot_xy = np.dot(x, y)
print("Dot product between x and y:\n", dot_xy)

# 6. Concatenation
x_with_y = np.vstack((x, y))
print("Vertical stack of x and y:\n", x_with_y)

v_with_w = np.column_stack((v, w))
print("Column stack of v and w:\n", v_with_w)

# 7. Concatenate x with v (reshape v first)
v_reshaped = v.reshape(1, -1)  # makes it 2D
x_with_v = np.vstack((x, v_reshaped))
print("x concatenated with reshaped v:\n", x_with_v)


x + y:
 [[ 6  8]
 [10 13]]
x - y:
 [[-4 -4]
 [-4 -3]]
x * 3:
 [[ 3  6]
 [ 9 15]]
v * 2:
 [18 20]
x squared:
 [[ 1  4]
 [ 9 25]]
Dot product between v and w: 219
Dot product between x and v:
 [29 77]
Dot product between x and y:
 [[19 22]
 [50 58]]
Vertical stack of x and y:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Column stack of v and w:
 [[ 9 11]
 [10 12]]
x concatenated with reshaped v:
 [[ 1  2]
 [ 3  5]
 [ 9 10]]


In [ ]:
# Problem 4
import numpy as np

# Matrices
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# Identity matrix
I = np.eye(2, dtype=int)

# Inverse of A
A_inv = np.linalg.inv(A)

# Multiply A with its inverse
AdotAinv = np.dot(A, A_inv)

# Round the result to nearest integer for comparison
AdotAinv_int = np.round(AdotAinv).astype(int)
print("A * A_inv (rounded to int):\n", AdotAinv_int)

# Check if it's equal to identity matrix
if np.array_equal(AdotAinv_int, I):
    print("True")
else:
    print("False")


A * A_inv (rounded to int):
 [[1 0]
 [0 1]]
True


In [ ]:
import numpy as np

# Matrices
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# Dot products
AdotB = np.dot(A, B)
BdotA = np.dot(B, A)

print("A · B:\n", AdotB)
print("B · A:\n", BdotA)

# Check equality
if np.array_equal(AdotB, BdotA):
    print("Both are equal")
else:
    print("Not equal")


A · B:
 [[23 13]
 [51 29]]
B · A:
 [[36 44]
 [13 16]]
Not equal


In [ ]:
# Solving a linear system
import numpy as np

# Coefficient matrix
A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3,  1, -1]])

# Constants vector
B = np.array([[-1],
              [-3],
              [9]])

# Solve using inverse
A_inv = np.linalg.inv(A)
x = np.dot(A_inv, B)

print("Solution x:\n", x)


Solution x:
 [[ 2.]
 [ 1.]
 [-2.]]


In [ ]:
# Experiment: Comparing Python lists vs NumPy arrays
import time
import numpy as np

# Create large lists
list1 = list(range(1_000_000))
list2 = list(range(1_000_000))

# Element-wise addition using Python lists
start_time = time.time()
list_result = [list1[i] + list2[i] for i in range(1_000_000)]
end_time = time.time()
print("Time taken for element-wise addition using Python lists:",
      end_time - start_time, "seconds")

# Element-wise addition using NumPy arrays
arr1 = np.array(list1)
arr2 = np.array(list2)

start_time = time.time()
arr_result = arr1 + arr2
end_time = time.time()
print("Time taken using NumPy arrays:",
      end_time - start_time, "seconds")


Time taken for element-wise addition using Python lists: 0.1214439868927002 seconds
Time taken using NumPy arrays: 0.005051851272583008 seconds


In [ ]:
# Element-wise multiplication: Python lists vs NumPy arrays
import time
import numpy as np

# Create large lists
list1 = list(range(1_000_000))
list2 = list(range(1_000_000))

# Element-wise multiplication using Python lists
start_time = time.time()
list_result = [list1[i] * list2[i] for i in range(1_000_000)]
end_time = time.time()
print("Time taken for element-wise multiplication using Python lists:",
      end_time - start_time, "seconds")

# Element-wise multiplication using NumPy arrays
arr1 = np.array(list1)
arr2 = np.array(list2)

start_time = time.time()
arr_result = arr1 * arr2
end_time = time.time()
print("Time taken using NumPy arrays:",
      end_time - start_time, "seconds")


Time taken for element-wise multiplication using Python lists: 0.13102102279663086 seconds
Time taken using NumPy arrays: 0.004199981689453125 seconds


In [ ]:
# Dot product: Python lists vs NumPy arrays
import time
import numpy as np

# Create large lists
list1 = list(range(1_000_000))
list2 = list(range(1_000_000))

# Dot product using Python lists
start_time = time.time()
dot_product_list = 0
for i in range(1_000_000):
    dot_product_list += list1[i] * list2[i]
end_time = time.time()

print("Dot product using Python lists:", dot_product_list)
print("Time taken (Python lists):", end_time - start_time, "seconds")

# Dot product using NumPy arrays
arr1 = np.array(list1)
arr2 = np.array(list2)

start_time = time.time()
dot_product_numpy = np.dot(arr1, arr2)
end_time = time.time()

print("\nDot product using NumPy:", dot_product_numpy)
print("Time taken (NumPy):", end_time - start_time, "seconds")


Dot product using Python lists: 333332833333500000
Time taken (Python lists): 0.4252486228942871 seconds

Dot product using NumPy: 333332833333500000
Time taken (NumPy): 0.002358675003051758 seconds


In [ ]:
# Matrix multiplication: Python lists vs NumPy arrays
import time
import numpy as np
import random

# Matrix size
size = 1000

# Create two random matrices using Python lists
matrix1 = [[random.randint(0, 9) for _ in range(size)] for _ in range(size)]
matrix2 = [[random.randint(0, 9) for _ in range(size)] for _ in range(size)]

# Matrix multiplication using Python lists (manual)
start_time = time.time()

result_list = [[0]*size for _ in range(size)]
for i in range(size):
    for j in range(size):
        sum_val = 0
        for k in range(size):
            sum_val += matrix1[i][k] * matrix2[k][j]
        result_list[i][j] = sum_val

end_time = time.time()
print("Time taken for matrix multiplication using Python lists:", end_time - start_time, "seconds")

# Matrix multiplication using NumPy arrays
arr1 = np.array(matrix1)
arr2 = np.array(matrix2)

start_time = time.time()
result_numpy = np.dot(arr1, arr2)
end_time = time.time()
print("Time taken for matrix multiplication using NumPy arrays:", end_time - start_time, "seconds")


Time taken for matrix multiplication using Python lists: 252.586678981781 seconds
Time taken for matrix multiplication using NumPy arrays: 1.7489759922027588 seconds
